stages:
  descarga_kaggle_reviews:
    cmd: python scripts/data_ingestion/descarga_kaggle_reviews.py
    deps:
    - scripts/data_ingestion/descarga_kaggle_reviews.py
    outs:
    - data/landing/sephora/raw
    - data/landing/ulta/raw
  conversion_a_delta:
    cmd: python scripts/data_cleaning/conversion_a_delta.py
    deps:
    - data/landing/sephora/raw
    - data/landing/ulta/raw
    - scripts/data_cleaning/conversion_a_delta.py
    outs:
    - data/landing/sephora/delta
    - data/landing/ulta/delta
  trusted_cleaning:
    cmd: python scripts/data_cleaning/trusted_clean_driver.py
    deps:
    - data/landing/sephora/delta
    - data/landing/ulta/delta
    - scripts/data_cleaning/trusted_clean_driver.py
    - scripts/data_cleaning/trusted_clean_single.py
    outs:
    - data/trusted/sephora_clean
    - data/trusted/ulta_clean
