stages:
  descarga_kaggle_reviews:
    cmd: python scripts/data_ingestion/descarga_kaggle_reviews.py
    deps:
    - scripts/data_ingestion/descarga_kaggle_reviews.py
    outs:
    - data/landing/sephora/raw
    - data/landing/ulta/raw
  conversion_a_delta:
    cmd: python scripts/data_cleaning/conversion_a_delta.py
    deps:
    - data/landing/sephora/raw
    - data/landing/ulta/raw
    - scripts/data_cleaning/conversion_a_delta.py
    outs:
    - data/landing/sephora/delta
    - data/landing/ulta/parquet
  trusted_cleaning:
    cmd: python scripts/data_cleaning/trusted_clean_driver.py
    deps:
    - data/landing/sephora/delta
    - scripts/data_cleaning/trusted_clean_driver.py
    - scripts/data_cleaning/trusted_clean_single.py
    - scripts/data_cleaning/utils_text.py
    outs:
    - data/trusted/sephora_clean
  build_model_input:
    cmd: python scripts/data_cleaning/filtrar_reviews_base.py
    deps:
    - data/trusted/sephora_clean
    - scripts/data_cleaning/filtrar_reviews_base.py
    outs:
    - data/exploitation/modelos_input/reviews_base_csv
    - data/exploitation/modelos_input/reviews_base_delta
    - data/exploitation/modelos_input/reviews_base_parquet
