sampling:
  frac: 0.30
  by: sentiment_category
  seed: 42
  format: delta
  coalesce: 64
  balance: true   # muestreo balanceado por clase

eda_compare_full_vs_30:
  a: data/trusted/reviews_full
  b: data/trusted/reviews_sample_30pct
  outdir: reports/eda/compare_full_vs_30
  by: sentiment_category
  input_format: auto
  tokenizer: albert-base-v2
  sample_rows: 120000
  max_len: 128
  clip_tokens: true
  silence_tokenizer_warnings: true

model:
  albert:
    num_labels: 3
    labels: ["negative", "neutral", "positive"]   # ORDEN CANÓNICO
    label2id:
      negative: 0
      neutral: 1
      positive: 2
    id2label:
      "0": "negative"
      "1": "neutral"
      "2": "positive"
    clean_output: true
    model_name: albert-base-v2
    max_len: 192
    batch: 64
    eval_batch: 128
    epochs: 4
    label_smoothing_factor: 0.05
    lr: 2e-5
    weight_decay: 0.05
    seed: 42
    optim: adamw_torch_fused          # en HF>=4.56 usar adamw_torch si hace falta
    prefer_cuda: 1
    bf16: true
    fp16: false
    gradient_checkpointing: false
    torch_compile: true
    torch_compile_mode: max-autotune
    tokenize_num_proc: 8
    eval_strategy: epoch
    save_strategy: epoch
    save_total_limit: 2
    patience: 2
    load_best_model_at_end: true
    text_col: review_text_clean
    label_col: label3                 # si no existe, se deriva desde rating
    rating_col: rating
    dataloader_num_workers: 8
    dataloader_prefetch_factor: 4
    dataloader_pin_memory: true
    dataloader_persistent_workers: true
    resume_from_last: true
training:
  class_weights:
    mode: manual
    manual: [1.8, 1.35, 0.6]

mlflow:
  enable: true
  experiment: Sentidata
  tracking_uri: "file:./mlruns"
  run_name: albert_sample_30pct
  tags:
    stage: train

rf:
  text_col: review_text
  label_col: null            # si no hay label explícita, se deriva de rating
  rating_col: rating
  preproc:
    use_lemma: true
    language: en
  tfidf:
    max_features: 50000
    ngram_range: [1, 2]
    min_df: 3
    max_df: 0.95
    stop_words: english
  features:
    add_neg_lexicon: true
    add_contrast_markers: true
    add_len: true
  model_params:
    n_estimators: 100 #inicialmente 400
    max_depth: null
    class_weight: balanced
    n_jobs: -1
seed: 42

# =========================
# Paths (merge trusted)
# =========================
paths:
  reviews_full: data/trusted/reviews_full
  product_info: data/trusted/sephora_clean/product_info
  merged_out: data/trusted/reviews_product_info_clean_full

merge_reviews_product_info:
  input_format: auto        # auto | delta | parquet
  output_format: delta      # delta | parquet
  repartition: 0            # evitar shuffle
  coalesce: 64              # compacta sin shuffle (ajusta si memoria)
  broadcast_product_info: "true"
  product_prefix: pinfo_

# =========================
# ATE (trusted)
# =========================
ate_trusted:
  input_path: data/trusted/reviews_product_info_clean_full
  input_format: delta
  text_col: review_text_clean
  id_col: review_id
  ontology_json: configs/aspects_en.json
  output_dir: data/trusted/ate
  train_filename: train.jsonl
  valid_filename: valid.jsonl
  sample_fraction: 0.2     # 0–1: muestreo de reviews
  max_reviews: 300000      # 0 = sin límite
  train_valid_split: 0.9
  keep_neg_ratio: 0.2
  seed: 13

ate_train:
  model_name: roberta-base
  output_dir: models/ate_roberta_base
  epochs: 4
  lr: 2e-5
  batch_size: 32
  grad_accum: 2
  max_length: 192
  # precisión y rendimiento
  fp16: false          
  bf16: true         
  grad_checkpoint: false
  dataloader_workers: 8
  # datos
  train_path: data/trusted/ate/train.jsonl
  valid_path: data/trusted/ate/valid.jsonl

ate_infer:
  model_dir: models/ate_roberta_base
  input_path: data/trusted/reviews_product_info_clean_full
  input_format: delta
  text_col: review_text_clean
  id_col: review_id
  output_parquet: reports/absa/ate_spans.parquet
  max_length: 192
  batch_size: 128
  flush_rows: 25000

ate_map:
  spans_parquet: reports/absa/ate_spans.parquet
  ontology_json: configs/aspects_en.json
  output_parquet: reports/absa/ate_spans_mapped.parquet
  threshold: 0.45

# =========================
# Ontology (English)
# =========================
aspects_ontology_en:
  fragrance: [fragrance, scent, smell, aroma, perfume, notes, odor, fragrant]
  longevity: [longevity, long-lasting, lasting, wear time, duration, staying power]
  sillage: [sillage, projection, trail, leaves a trail]
  price: [price, price point, cost, value, worth, expensive, cheap, overpriced]
  packaging: [packaging, bottle, cap, pump, box, container, design]
  texture: [texture, consistency, feel, thick, thin, creamy, watery, sticky, greasy, lightweight, silky]
  hydration: [hydration, moisturizing, hydrating, moisture, drying, dehydrating]
  application: [application, apply, applies, spreads, absorbs, glides, blendability, easy to use]
  finish: [finish, matte, dewy, glowy, glossy, sheen, shine]
  irritation: [irritation, irritates, sting, burning, redness, itch, breakout, allergic, sensitivity]
  ingredients: [ingredients, alcohol, parabens, sulfates, silicones, fragrance-free, clean, formula]
  effectiveness: [effectiveness, works, results, performance, improvement, does nothing]

absa:
  id_col: review_id
  span_text_col: aspect_span
  category_col: aspect_norm
  sentiment_col: pred_3
  text_col: null
  numeric_sentiment_col: null
  neg_threshold: 2.0
  pos_threshold: 4.0
  repartition: null
  output_dir: reports/absa/final_all

infer_sentiment_full_pandas:
  model_dir: models/albert_sample_30pct
  input_path: data/trusted/reviews_full_snapshot.parquet
  input_format: parquet
  output_parquet: reports/albert_sample_30pct/infer_full_pandas/predictions.parquet
  id_col: review_id
  text_col: review_text_clean
  batch_size: 64
  max_length: 192