model:
  albert:
    model_name: albert-base-v2
    num_labels: 3
    max_len: 192
    batch: 128
    eval_batch: 128
    epochs: 4
    label_smoothing_factor: 0.05
    lr: 2e-5
    weight_decay: 0.05
    seed: 42
    optim: adamw_torch_fused          # <- en 4.56.0 usa adamw_torch (no adamw_hf)
    prefer_cuda: 1
    bf16: true
    fp16: false
    gradient_checkpointing: false
    torch_compile: true
    torch_compile_mode: max-autotune
    tokenize_num_proc: 6    
    eval_strategy: epoch
    save_strategy: epoch
    save_total_limit: 2
    patience: 2
    load_best_model_at_end: true
    text_col: review_text_clean
    label_col: label3           # si no existe, se deriva desde rating
    rating_col: rating
    dataloader_num_workers: 8
    dataloader_prefetch_factor: 2
    dataloader_pin_memory: true
    dataloader_persistent_workers: true
    resume_from_last: true
training:
  class_weights:
    mode: manual
    manual: [1.8, 1.35, 0.6]

mlflow:
  enable: true
  experiment: Sentidata
  tracking_uri: "file:./mlruns"
  run_name: albert_sample_30pct
  tags:
    stage: train