artifact_location: file:///home/davidmc/MASTER_BIGDATA/TFM/TFM-Sentidata/models/mlflow_runs/0
creation_time: 1753011826741
experiment_id: '0'
last_update_time: 1753011826741
lifecycle_stage: active
name: Default
